heat_template_version: 2015-04-30

description: customization template

parameters:
  enm_rhel6_base_image_name:
    type: string

  enm_internal_network_name:
    type: string

  enm_security_group_name:
    type: comma_delimited_list

  flavor_4vC8M:
    type: string

  key_name:
    type: string

  use_config_drive:
    type: boolean
    default: true

  internal_netmask:
    type: string

  lvs_fcaps_option_FM:
    type: string

  service_registry_dns_port:
    type: string
    default: 53

  service_registry_datacenter:
    type: string
    default: dc1

  service_registry_domain:
    type: string
    default: enm

  serviceregistry_internal_ip_list:
    type: comma_delimited_list

  timezone:
    type: string

  enm_external_network_name:
    type: string

  provider_routed_network_name:
    type: string

  ms3ppsnmpfm_instances:
    type: string
    default: 2

  deployment_id:
    type: string

  ms3ppsnmpfm_internal_ip_list:
    type: comma_delimited_list

resources:
  ms3ppsnmpfm:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: ms3ppsnmpfm_instances }
      resource_def:
        type: customization_definition.yaml
        properties:
          NodeIndex: '%index%'
          deployment_id: { get_param: deployment_id }
          ms3ppsnmpfm_internal_ip_list: { get_param: ms3ppsnmpfm_internal_ip_list }
          enm_rhel6_base_image_name: { get_param: enm_rhel6_base_image_name }
          enm_internal_network_name: { get_param: enm_internal_network_name }
          enm_security_group_name: { get_param: enm_security_group_name }
          flavor_4vC8M: { get_param: flavor_4vC8M }
          key_name: { get_param: key_name }
          service_registry_dns_port: { get_param : service_registry_dns_port }
          service_registry_datacenter: { get_param : service_registry_datacenter }
          service_registry_domain: { get_param : service_registry_domain }
          serviceregistry_internal_ip_list: { get_param : serviceregistry_internal_ip_list }
          lvs_fcaps_option_FM: { get_param : lvs_fcaps_option_FM }
          internal_netmask: { get_param : internal_netmask }
          timezone: { get_param : timezone }
          enm_external_network_name: { get_param : enm_external_network_name }
          provider_routed_network_name: { get_param : provider_routed_network_name }
